tasks:
  - before: printf "$(date -Ins) $GITPOD_WORKSPACE_ID\n" >> /workspace/.before1
    init: printf "$(date -Ins) $GITPOD_WORKSPACE_ID\n" >> /workspace/.init1
    prebuild: printf "$(date -Ins) $GITPOD_WORKSPACE_ID\n" >> /workspace/.prebuild1
  - openMode: split-right
    before: printf "$(date -Ins) $GITPOD_WORKSPACE_ID\n" >> /workspace/.before2
    init: printf "$(date -Ins) $GITPOD_WORKSPACE_ID\n" >> /workspace/.init2
    prebuild: printf "$(date -Ins) $GITPOD_WORKSPACE_ID\n" >> /workspace/.prebuild2
    command: cat /workspace/.{before,init,prebuild}{1,2} | sort

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
